platform :ios, '10.0'
use_frameworks!

target 'Redirapp_Example' do
  pod 'Redirapp', :path => '../'
  
  target 'Redirapp_Tests' do
    inherit! :search_paths

   pod 'Quick'
   pod 'Nimble'
  end
end
