use_frameworks!

target 'Redirapp_Example' do
  pod 'Redirapp', :path => '../'

  target 'Redirapp_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
